dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 2.6 ] ||
  \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- if [[ $TRAVIS_PYTHON_VERSION = 2.* ]]; then pip install futures; fi
- pip install pyflakes
- $no_pylint || pip install pylint
- pip install docutils
script:
- python setup.py build
- python tests/run-tests -v
- private/check-rst
- private/update-coverage
- git diff --exit-code
- python setup.py install
- cd / && python -m pydiatra --version
- pyXdiatra=py${TRAVIS_PYTHON_VERSION%.*}diatra
- $pyXdiatra --version
- export MANPATH=$VIRTUAL_ENV/share/man MANWIDTH=80
- man 1 pydiatra | grep -A 15 -w PYDIATRA
- man 1 $pyXdiatra | grep -A 15 -w PYDIATRA
- private/run-pydiatra
- private/run-pyflakes
- $no_pylint || private/run-pylint

# vim:ts=2 sts=2 sw=2 et
