language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.7-dev"
before_install:
- no_pylint=true
- \[ "$TRAVIS_PYTHON_VERSION" = 2.6 ] ||
  \[ "$TRAVIS_PYTHON_VERSION" = 3.2 ] ||
  [[ "$TRAVIS_PYTHON_VERSION" =~ dev ]] ||
  no_pylint=false
install:
- \[ "${TRAVIS_PYTHON_VERSION##2*}" != '' ] || pip install futures
- pip install pyflakes
- $no_pylint || pip install pylint
- pip install docutils
script:
- python setup.py build
- python tests/run-tests -v
- private/run-pyflakes
- $no_pylint || private/run-pylint
- ls *.rst | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null
