language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
install:
- pip install docutils
script:
- python tests/run-tests -v
- find -name '*.rst' | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null
