dist: trusty
language: python
jobs:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
    dist: xenial
  - python: "3.8-dev"
    dist: xenial
branches:
  except:
  - appveyor
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then if_pylint=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then if_pylint=:; fi
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then if_pylint=:; fi
- pyXdiatra=py${TRAVIS_PYTHON_VERSION%.*}diatra
install:
- pip install "futures; python_version < '3'"
- pip install $pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then
    printf '\n\n    CONSTANT = ignore\n' >> $VIRTUAL_ENV/lib/python*/site-packages/pyflakes/checker.py;
  fi
- $if_pylint pip install pylint
- pip install docutils
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- python setup.py build
- python tests/run-tests -v
- private/check-rst
- private/update-coverage
- git diff --exit-code
- python setup.py install
- pushd /
- python -m pydiatra --version
- $pyXdiatra --version
- export MANPATH=$VIRTUAL_ENV/share/man MANWIDTH=80
- man 1 pydiatra | grep -A 15 -w PYDIATRA
- man 1 $pyXdiatra | grep -A 15 -w PYDIATRA
- popd
- private/run-pydiatra
- private/run-pyflakes
- $if_pylint private/run-pylint
- rm -rvf $VIRTUAL_ENV/lib/python*/site-packages/pydiatra*
- pip install .

# vim:ts=2 sts=2 sw=2 et
