language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- nightly
install:
- pip install pyflakes
- pip install docutils
script:
- python setup.py build
- python tests/run-tests -v
- \[ "${TRAVIS_PYTHON_VERSION##3*}" != '' ] || private/run-pyflakes
- ls *.rst | xargs -L1 -t -I{} rst2xml.py --strict {} /dev/null
