class LRParser:
    # ...
    def parsedebug(self, *args, **kwargs):
        # ...
        debug.info('PLY: PARSE DEBUG START')
        # ...
    # ...

## embedded-code-copy ply.yacc

# vim:ts=4 sts=4 sw=4 et syntax=python
