#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u

if [ $# -lt 3 ]
then
    printf '%s <v1> <v2> <dir>...\n' "$0" >&2
    exit 1
fi

v1="$1"
v2="$2"
shift 2
here=$(dirname "$0")
v1=$(git rev-parse --short "$v1")
v2=$(git rev-parse --short "$v2")
tmpdir=$(mktemp -d -t pydiatra.XXXXXX)
mkdir "$tmpdir/$v1" "$tmpdir/$v2"
git -C "$here/.." archive "$v1" --prefix=p1/ | tar -C "$tmpdir/" -x
git -C "$here/.." archive "$v2" --prefix=p2/ | tar -C "$tmpdir/" -x
ack --python -f "$@" --print0 | xargs -0 -n99 "$tmpdir/p1/py2diatra" -jauto -- > "$tmpdir/$v1/py2" || true
ack --python -f "$@" --print0 | xargs -0 -n99 "$tmpdir/p1/py3diatra" -jauto -- > "$tmpdir/$v1/py3" || true
ack --python -f "$@" --print0 | xargs -0 -n99 "$tmpdir/p2/py2diatra" -jauto -- > "$tmpdir/$v2/py2" || true
ack --python -f "$@" --print0 | xargs -0 -n99 "$tmpdir/p2/py3diatra" -jauto -- > "$tmpdir/$v2/py3" || true
cd "$tmpdir"
diff -U0 -r "$v1" "$v2" || true
cd /
rm -rf "$tmpdir"

# vim:ts=4 sts=4 sw=4 et
