#!/bin/sh

# Copyright © 2015-2017 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u
PYTHON=${PYTHON:-python3}
[ -n "${TRAVIS_PYTHON_VERSION:-}" ] && PYTHON=python
"$PYTHON" -m pylint --version >/dev/null || exit 1
if [ $# -eq 0 ]
then
    pyre='^#!.*python'
    pyver=$("$PYTHON" -c 'import sys; print(sys.version_info[0])')
    [ "$pyver" = 2 ] && pyre="${pyre}(?!3)"
    pyscripts=$(grep -l -r -P "$pyre" . | grep -v /build/)
    set -- pydiatra setup.py tests/*.py $pyscripts
fi
if [ -n "${TRAVIS_PYTHON_VERSION:-}" ]
then
    # https://github.com/PyCQA/pylint/issues/73
    set -- --ignored-modules=distutils "$@"
fi
set -- --load-plugins=pylint.extensions.check_elif "$@"
log=$(mktemp -t pylint.XXXXXX)
"$PYTHON" -m pylint "$@" > "$log" || [ $? != 1 ]
! grep '^\w:' "$log" \
| grep -v ': missing-docstring \[\w' \
| grep -v -P '^\w: (?!pydiatra/).+: missing-docstring ' \
| grep -v -P '^\w: .+/__main__[.]py:.+: missing-docstring ' \
| grep -v ": redefined-builtin \\[.*\\] Redefining built-in 'file'" \
| LC_ALL=C sort -k2 \
| grep '.' || exit 1
rm "$log"

# vim:ts=4 sts=4 sw=4 et
