#!/bin/sh

# Copyright © 2015-2017 Jakub Wilk <jwilk@jwilk.net>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set -e -u

pyflakes=$(command -v pyflakes) || { echo pyflakes not found >&2; exit 1; }

PYTHON=${PYTHON:-python3}
[ -n "${TRAVIS_PYTHON_VERSION:-}" ] && PYTHON=python

if [ $# -eq 0 ]
then
    pyre='^#!.*python'
    pyver=$("$PYTHON" -c 'import sys; print(sys.version_info[0])')
    [ "$pyver" = 2 ] && pyre="${pyre}(?!3)"
    pyscripts=$(grep -l -r -P "$pyre" . | grep -v /build/)
    set -- $(find . '(' -name build -prune -false ')' -o -name '*.py') $pyscripts
fi

exec "$PYTHON" "$pyflakes" "$@"

# vim:ts=4 sts=4 sw=4 et
