#!/bin/sh
set -e -u
export version=${1:?"no version number provided"}
set -x
dch -m -v "$version" -u low -c doc/changelog
perl -pi -e 's/^:version: \S+ \K[\w.]+/$ENV{version}/' doc/manpage.rst
perl -pi -e 's/^__version__ = '"'"'\K[\w.]+/$ENV{version}/' pydiatra/__init__.py
